# Site settings
url: "http://bergdollinsurance.com" # the base hostname & protocol for your site

# Build settings
markdown: rdiscount
timezone: America/New_York
source: .
destination: ./_site
layouts_dir: ./_layouts
plugins_dir: ./_plugins
includes_dir: ./_includes
sass:
  sass_dir: css
  style: compressed
gems:
  - octopress-autoprefixer
collections:
  sections:
    output: true
    permalink: /sections/:path/
exclude: [js/plugins/, js/raw/]
defaults: 
  -
    scope:
      path: ""
      type: sections
    values:
      layout: bare

slim:
  pretty: true
  format: html5