# Site settings
title: Bergdoll Insurance
email: your-email@domain.com
phoneNumber: "480 315 0400"
facebookUrl: "https://www.facebook.com/BergdollInsurance/"
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4040" # the base hostname & protocol for your site

collections:
  sections:
    output: false

# Build settings
port: 4040
markdown: rdiscount
timezone: America/New_York
source: .
destination: ./_site
layouts_dir: ./_layouts
plugins_dir: ./_plugins
includes_dir: ./_includes
sass:
  sass_dir: css
  style: compressed
gems:
  - octopress-autoprefixer
exclude: [js/plugins/, js/raw/]
defaults: 
  -
    scope:
      path: ""
      type: sections
    values:
      layout: bare

slim:
  pretty: true
  format: html5