# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
port: 4040
markdown: rdiscount
timezone: America/New_York
source: .
destination: ./_site
layouts: ./_layouts
plugins: ./_plugins
sass:
  sass_dir: css
  style: compressed
gems:
  - octopress-autoprefixer
collections:
  sections:
    output: true
    permalink: /sections/:path/
exclude: [js/plugins/, js/raw/]
defaults: 
  -
    scope:
      path: ""
      type: sections
    values:
      layout: bare